---
title: "Izzy Flood"
---

## Effective Teamwork



In this article, ["6 Tips For Effective Teamwork"](https://www.linkedin.com/pulse/6-tips-effective-teamwork-dr-david-burkus-iaaqc/), on teamwork, Doctor David Burkus identifies 6 methods to have a great team.

1. Set Clear Goals: Setting goals at the team and individual level allows each person in the group to know what they're working towards.

2. Communicate Activity: Team members must keep their teammates updated on any actions they've taken towards the project. This is done so that everyone is on the same page.

3. Understand Differences: On a team, each individual will have different beliefs, strengths, and weaknesses. Knowing how to maximize everyone's strengths can create synergy.

4. Create Psychological Safety: Allowing team members to be vulnerable and make mistakes is vital. 

5. Disagree Respectfully: Team members must be able to listen and actively attempt to understand why another team member might take a different approach to a challenge. In doing so, the team develops resiliency and understanding.

6. Celebrate Small Wins: Celebrating small wins for the team builds morale and momentum in achieiving the larger goal.

