---
title: "Zach M Effective"
format: html
---

###Summary

The UC Berkeley People & Culture website offers a range of HR-related services managed by Central Services, which include records management, business systems support, and compensation and benefits. The website also details initiatives for Staff Engagement & Belonging (SE&B), focusing on community, inclusivity, and cultural fluency, as well as support from Employee & Labor Relations (ELR). Furthermore, UC Berkeley prioritizes employee growth and development and utilizes the 'Achieve Together' program for performance management. Crucially, the source provides guidance on building effective teams, emphasizing leadership based on trust and loyalty, valuing employee ideas and feelings, promoting clear communication and cooperation, and establishing team values, goals, and ground rules through consensus.

##Link

["Steps to Building an Effective Team"](https://hr.berkeley.edu/hr-network/central-guide-managing-hr/managing-hr/interaction/team-building/steps)

